config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/DSpace:
      branch: master
      repo: https://github.com/openaire/DSpace
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.steel_thankful_frog.sh
        container: qc.acc_ebony_anxious_gerbil
  QC.Doc:
    repos:
      github.com/openaire/DSpace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_rational_okapi.sh
        container: qc.doc_isabelline_playful_antelope
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.ginger_kind_bullfrog.sh
        container: qc.doc_khaki_dizzy_crane
      github.com/openaire/DSpace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_vigilant_hamster.sh
        container: qc.doc_jet_feisty_chimpanzee
  QC.Lic:
    repos:
      github.com/openaire/DSpace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.butterscotch_tactful_serval.sh
        container: qc.lic_crimson_zany_hedgehog
  QC.Sty:
    repos:
      github.com/openaire/DSpace checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_timid_chameleon.sh
        container: qc.sty_navy_trustworthy_dugong
      github.com/openaire/DSpace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.raven_bright_dugong.sh
        container: qc.sty_grege_frugal_ostrich
      github.com/openaire/DSpace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paprika_restless_lobster.sh
        container: qc.sty_violet_protective_lobster
  QC.Ver:
    repos:
      github.com/openaire/DSpace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.strawberry_sociable_gibbon.sh
        container: qc.ver_mist_perky_cormorant
timeout: 5400
