config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/DSpace:
      branch: master
      repo: https://github.com/openaire/DSpace
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_wise_goose.sh
        container: qc.acc_storm_nervous_baboon
  QC.Doc:
    repos:
      github.com/openaire/DSpace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_sad_squid.sh
        container: qc.doc_pearl_timid_goose
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_kind_kangaroo.sh
        container: qc.doc_lime_savvy_mink
      github.com/openaire/DSpace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_apathetic_seahorse.sh
        container: qc.doc_olive_vibrant_panther
  QC.Lic:
    repos:
      github.com/openaire/DSpace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.mahogany_shy_ferret.sh
        container: qc.lic_pearl_dizzy_donkey
  QC.Sty:
    repos:
      github.com/openaire/DSpace checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.emerald_honest_octopus.sh
        container: qc.sty_jasmine_rational_iguana
      github.com/openaire/DSpace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grape_helpful_capybara.sh
        container: qc.sty_celadon_diplomatic_unicorn
      github.com/openaire/DSpace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_tactful_komodo.sh
        container: qc.sty_ceru_unique_echidna
  QC.Ver:
    repos:
      github.com/openaire/DSpace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_mysterious_frog.sh
        container: qc.ver_linen_alert_phoenix
timeout: 5400
