config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/DSpace:
      branch: master
      repo: https://github.com/openaire/DSpace
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.fern_trustworthy_seahorse.sh
        container: qc.acc_cardamom_responsible_angelfish
  QC.Doc:
    repos:
      github.com/openaire/DSpace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.red_humble_tarantula.sh
        container: qc.doc_bone_daring_cobra
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.salmon_frugal_finch.sh
        container: qc.doc_cerise_funny_coyote
      github.com/openaire/DSpace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wave_visionary_reindeer.sh
        container: qc.doc_grape_devoted_crocodile
  QC.Lic:
    repos:
      github.com/openaire/DSpace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_forgiving_stork.sh
        container: qc.lic_storm_proactive_cougar
  QC.Sty:
    repos:
      github.com/openaire/DSpace checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.dawn_zany_nighthawk.sh
        container: qc.sty_carmine_sincere_chameleon
      github.com/openaire/DSpace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_independent_hippopotamus.sh
        container: qc.sty_denim_confident_spider
      github.com/openaire/DSpace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.glacier_enigmatic_gecko.sh
        container: qc.sty_harlequin_reserved_manatee
  QC.Ver:
    repos:
      github.com/openaire/DSpace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunset_timid_gnu.sh
        container: qc.ver_emerald_methodical_komodo
timeout: 5400
